# Generated by Django 4.2.5 on 2023-11-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('description_1', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_1')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_1')),
                ('description_2', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_2')),
                ('description_3', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_3')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_3')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
                ('url', models.SlugField(max_length=160, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('compound', models.TextField(blank=True, default='', max_length=1000, verbose_name='Состав')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объем (мл,гр)')),
                ('description', models.TextField(blank=True, default='', max_length=4000, verbose_name='Описание')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет')),
                ('country', models.CharField(blank=True, default='', max_length=50, verbose_name='Страна производитель')),
                ('density', models.CharField(blank=True, default='', max_length=50, verbose_name='Плотность')),
                ('effect', models.CharField(blank=True, default='', max_length=50, verbose_name='Эффект')),
                ('consistency', models.CharField(blank=True, default='', max_length=50, verbose_name='Консистенция')),
                ('rigidity', models.CharField(blank=True, default='', max_length=50, verbose_name='Жесткость')),
                ('shade', models.CharField(blank=True, default='', max_length=50, verbose_name='Оттенок')),
                ('collection', models.CharField(blank=True, default='', max_length=50, verbose_name='Коллекция')),
                ('for_what', models.CharField(blank=True, choices=[('Для рук', 'Для рук'), ('Для ног', 'Для ног'), ('Для ногтей', 'Для ногтей')], default='', max_length=30, verbose_name='Для чего')),
                ('for_what_tools', models.CharField(blank=True, choices=[('Для маникюра', 'Для маникюра'), ('Для педикюра', 'Для педикюра')], default='', max_length=30, verbose_name='Для чего инструменты')),
                ('best_before_date', models.CharField(blank=True, default='', max_length=50, verbose_name='Срок годность')),
                ('where_buy', models.CharField(blank=True, default='', max_length=50, verbose_name='Где купить')),
                ('link', models.TextField(blank=True, default='', max_length=2000, verbose_name='Ссылка на товар')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название бренда')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название подкатегории')),
                ('url', models.SlugField(max_length=160, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Subsubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подподкатегория')),
                ('url', models.SlugField(max_length=160, verbose_name='URL')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subtitle', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подподкатегория',
                'verbose_name_plural': 'Подподкатегории',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.reviews', verbose_name='Родитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='продукт')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subsub',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='service.subsubtitle', verbose_name='Подподкатегория'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='service.subtitle', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='product',
            name='trademark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.trademark', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.article', verbose_name='Продукт')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.articlereview', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв статьи',
                'verbose_name_plural': 'Отзывы статей',
            },
        ),
    ]
