# Generated by Django 4.2.5 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trademark',
            field=models.CharField(max_length=255, verbose_name='Название торговой марки'),
        ),
    ]
