# Generated by Django 4.2.5 on 2023-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_before_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Срок годность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем (мл,гр)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='where_buy',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Где купить'),
        ),
    ]
