# Generated by Django 4.2.5 on 2023-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=160, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=160, verbose_name='URL'),
        ),
    ]
