# Generated by Django 4.2.5 on 2023-10-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_product_subtitle_alter_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подподкатегория')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subtitle', verbose_name='Подкатегория')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subsub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.subsubtitle', verbose_name='Подподкатегория'),
        ),
    ]
