# Generated by Django 4.2.5 on 2023-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_product_best_before_date_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(blank=True, choices=[('', 'default'), ('Для рук', 'for hands'), ('Для ног', 'for legs'), ('Для ногтей', 'for nails')], default='', max_length=30, verbose_name='Для чего'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what_tools',
            field=models.CharField(blank=True, choices=[('', 'default'), ('Для маникюра', 'for a manicure'), ('Для педикюра', 'for pedicure')], default='default', max_length=30, verbose_name='Для чего инструменты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL'),
        ),
    ]
