# Generated by Django 4.2.5 on 2023-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_product_for_what_alter_product_for_what_tools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(blank=True, choices=[('Для рук', 'для рук'), ('Для ног', 'for legs'), ('Для ногтей', 'for nails')], default='', max_length=30, verbose_name='Для чего'),
        ),
    ]
