# Generated by Django 4.2.5 on 2023-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_product_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(blank=True, choices=[('без сортировки', 'без сортировки'), ('Для рук', 'для рук'), ('Для ног', 'Для ног'), ('Для ногтей', 'Для ногтей')], default='Без сортировки', max_length=30, verbose_name='Для чего'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what_tools',
            field=models.CharField(blank=True, choices=[('без сортировки', 'без сортировки'), ('Для маникюра', 'Для маникюра'), ('Для педикюра', 'Для педикюра')], default='default', max_length=30, verbose_name='Для чего инструменты'),
        ),
    ]
