# Generated by Django 4.2.5 on 2023-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_product_for_what_alter_product_for_what_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(blank=True, choices=[('Для рук', 'для рук'), ('Для ног', 'Для ног'), ('Для ногтей', 'Для ногтей')], default='', max_length=30, verbose_name='Для чего'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what_tools',
            field=models.CharField(blank=True, choices=[('Для маникюра', 'Для маникюра'), ('Для педикюра', 'Для педикюра')], default='', max_length=30, verbose_name='Для чего инструменты'),
        ),
    ]
