# Generated by Django 4.2.5 on 2023-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_product_for_what_alter_product_for_what_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='product',
            name='consistency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Консистенция'),
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='product',
            name='effect',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Эффект'),
        ),
        migrations.AddField(
            model_name='product',
            name='rigidity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Жесткость'),
        ),
        migrations.AddField(
            model_name='product',
            name='shade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Оттенок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(blank=True, choices=[('Для рук', 'Для рук'), ('Для ног', 'Для ног'), ('Для ногтей', 'Для ногтей')], default='', max_length=30, verbose_name='Для чего'),
        ),
    ]
