# Generated by Django 4.2.5 on 2023-11-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_product_collection_product_consistency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('description_1', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_1')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_1')),
                ('description_2', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_2')),
                ('description_3', models.TextField(blank=True, default='', max_length=4000, verbose_name='Текст_3')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='Фото_3')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product', verbose_name='продукт'),
        ),
    ]
